### ISSUE TITLE
Remove Guava Dependency

### ISSUE THREAD

**Issue by christopherperry** [airbnb/okreplay#41] opened 2017-06-23 22:29 UTC
The `okreplay` artifact has a dependency on Guava. This has a big impact on method count, and will easily take an app over the limits of single dex. This is something we try to avoid on my team, and makes the library unusable. How many things does okreplay need from Guava? I'm sure you can easily replace these and remove this dependency.

**Comment by felipecsl** [comment] 2017-06-23 22:30
Duplicate of #38 and addressed on #40 😄

**Closed by felipecsl** 2017-06-23 22:30 UTC
